### ISSUE TITLE
Assignment 1: About Section 3.3, MC Control

### ISSUE THREAD

**Issue by mingming741** [cuhkrlcourse/ierg6130-assignment#1]
What is the usage of "occured_state_action_pair"? Why we only store the value at the first time? I think it will cause the length of all list in "self.returns" has only 1 element.

**Comment by pengzhenghao** [comment]
Thanks for pointing it out! The comment there is also confusing.

Let's discuss the story from another perspective. Our goal is **We want to know the exact Q value of a given (state, action) pair.**

In order to do that, we maintain a list for this (state, action) pair, that is: `self.returns[(state, action)]`, since `self.returns` is a dictionary whose key is a pair and value is a list. The Q value we want to get is the mean of such list `np.mean(self.returns[(state, action)])`.

Now let's take a look at how to fulfill the list with proper content.

Given an episode's trajectory (that is, one call to `self.train()`), we collect a series of observation and action: `s_0, a_0, s_1, a_1, ..., s_T, a_T`

We compute the value of a state-action pair `(s_t, a_t)` by `v(s_t, a_t) = gamma * v(s_t+1, a_t+1) + r_t`. Then we append the computed value into corresponding list: `self.returns[(s_t, a_t)].append(v(s_t, a_t))`.

Everything looks good, right? But a marginal case is ignored. What if a state-action pair occurs twice in one episode? In that case, you would have two values corresponding to one state-action pair. Which should we use? 

According to page 99 of the textbook, if `(s_t, a_t)` and `(s_t+k, a_t+k)` both exist in a trajectory, we take the early one, that is `(s_t, a_t)`.

So that's the usage of `occured_state_action_pair`. It helps us track whether one state-action pair happen multiple times in a trajectory of one episode. It makes sure in one call to `trainer.train()` we only add values to those state-action pair once, not multiple values.

It's not true that the `self.returns` would be all list with length 1, since we do not clear the `self.returns` so the lists keep expanding as the call to `trainer.train()`
