### ISSUE TITLE
Assignment3: Reward threshold for validating algorithms

### ISSUE THREAD

**Issue by kennymckormick** [cuhkrlcourse/ierg6130-assignment#3]
In assignment 3, no error log is printed if the trained agent gets a low reward. Does that mean all agents will achieve rewards larger than the set threshold if our codes work properly?

**Comment by pengzhenghao** [comment]
Since CartPole-v0 is a quiet easy environment, your algorithm should solve it easily, except the Pong environment at the end of assignment, which is a quiet hard environment.
On Mar 16, 2020, at 12:48, Haodong Duan <notifications@github.com> wrote:In assignment 3, no error log is printed if the trained agent gets a low reward. Does that mean all agents will achieve rewards larger than the set threshold if our codes work properly?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kennymckormick** [comment]
Thank you for the information!
